formatVersion: 1
inputs: {}
resources:
  Cloud_vSphere_Network_1:
    type: Cloud.vSphere.Network
    properties:
      networkType: existing
      tags:
        - key: 'devnet'
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
      image: CloudImage
      cpuCount: 1
      totalMemoryMB: 1024
      customizationSpec: CentOS
      networks:
        - network: '${resource.Cloud_vSphere_Network_1.id}'
          assignment: dynamic
      constraints:
        - tag: 'cloud:vsphere'
  Cloud_Ansible_1:
    type: Cloud.Ansible
    properties:
      host: '${resource.Cloud_vSphere_Machine_1.*}'
      osType: linux
      account: ansible
      username: root
      password: VMware1!
      maxConnectionRetries: 10
      groups:
        - AppServers
      playbooks:
        provision:
          - /etc/ansible/playbooks/centos.yml